### ISSUE TITLE
Passar todo o repositório para o inglês

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#332]
Essa issue deverá ser dividida em tasks.

## Comportamento esperado

Todo o repositório deve estar em ingles.

## *Comportamento atual

Parte ingles parte em portugues.

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MartinsLucas** [comment]
Duplicate of issue #305

**Comment by MartinsLucas** [comment]
Duplicate of issue #305
